[theme]
primaryColor = "#4ade80"
backgroundColor = "#000000"
secondaryBackgroundColor = "#18181b"
textColor = "#ededed"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
